### ISSUE TITLE
企业端：企业基本信息填写界面，所有字段均为必填字段，且字段前用*号标识。

### ISSUE THREAD

**Issue by liwenge100** [ovaphlow/hengda.billboard#100]

**Comment by ovaphlow** [comment]
？？？？？？

**Comment by liwenge100** [comment]
就是企业填写信息的时候，设置所有信息为必填项，除了备注，并且必填项前用星号标注
![Snipaste_2020-05-26_21-12-11](https://user-images.githubusercontent.com/65892973/82904834-98c1c280-9f95-11ea-8788-c270aab36d78.png)

**Comment by ovaphlow** [comment]
都是必填项的话，每个再加上星号是为了好看吗？

**Comment by ovaphlow** [comment]
企业
