### ISSUE TITLE
部署测试记录

### ISSUE THREAD

**Issue by ovaphlow** [ovaphlow/hengda.billboard#52]

**Comment by qiangxiazhanling** [comment]
微信小程序要求: 
1.服务器需要绑定域名并备案
2.需要ssl证书
3.开放80,443端口

**Comment by qiangxiazhanling** [comment]
5月7日
由于客户现有服务器未申请域名无法进行测试,所以提出租借服务器
租借服务器(47.95.203.76)

**Comment by qiangxiazhanling** [comment]
5月8日
服务器提供方提供的新服务器(39.102.80.159)可以远程登录
安装运行环境正常
部署后端服务并启动正常
部署前端服务由于没有ssl证书无法启动https服务无法满足微信小程序要求
服务器本机访问80,801,802端口页面正常
外网域名访问80,801,802端口无法加载
外网ip访问80,801,802端口无法加载
由于没有ssl证书不满足微信小程序要求并且外网无法访问 80,801,802端口,无法继续测试

**Comment by qiangxiazhanling** [comment]
5月9日
服务器(39.102.80.159) 端口 80 801 802 443 已开启 ssl 证书以部署到nginx 
完成小程序封装

**Comment by qiangxiazhanling** [comment]
5月11日
上传小程序代码版本(1.0.0)
设置代码版本(1.0.0)为预览版
开始功能测试

**Comment by qiangxiazhanling** [comment]
5月12日
开始 小程序端与企业端 功能测试

**Comment by qiangxiazhanling** [comment]
5月13日
提交合并代码

**Comment by qiangxiazhanling** [comment]
5月14日
等待李文革完成业务测试

**Comment by qiangxiazhanling** [comment]
5月14日
等待李文革完成业务测试,与客户沟通产品运营逻辑

**Comment by qiangxiazhanling** [comment]
5月16日
配合业务测试，修复底带宽下的数据库连接问题

**Comment by qiangxiazhanling** [comment]
5月18日
查看核对业务测试问题反馈，准备开始业务方测试

**Comment by qiangxiazhanling** [comment]
5月19日
开始业务方测试，前端项目移交给前端开发人员(外包)完成时间未知

**Comment by qiangxiazhanling** [comment]
5月20日
完善举报投诉功能数据的准确性

**Comment by qiangxiazhanling** [comment]
5月21日
合并提交代码，更新程序到演示服务器

**Comment by qiangxiazhanling** [comment]
5月22日
解决业务方测试时提出的问题

**Comment by ovaphlow** [comment]
外聘前端在调整首页后，首页的功能被改动了：多选的筛选器被改为单选。
